version: '3.4'

services:
  atletigo:
    image: ${DOCKER_REGISTRY-}atletigo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www:/var/www
      - /etc/nginx:/etc/nginx
      - /opt/deploy.sh:/opt/deploy.sh
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8450:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=apicert
      - ASPNETCORE_Kestrel__Certificates__Default__Path=certificates/aspnetapp.pfx