name: Deploy AtletiGo .NET App
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest code on VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@89.117.32.49 << 'EOF'
            cd /var/www/portfolio-backend
            git fetch --all
            git reset --hard origin/main
          EOF

      - name: Restart Docker Container on VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@89.117.32.49 << 'EOF'
            cd /var/www/portfolio-backend
            docker-compose down
            docker-compose up -d --build
          EOF
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}